### ISSUE TITLE
Todo List, 30 Jan meeting

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/BHL#1]
- [x] Change 'subject' to 'species'
- [x] Remove 'hide old marks'
- [x] Change 'Read this page on BHL'
- [x] add some Field Guide examples
- [x] add a Tutorial
- [x] Remove 'bookplate' from types list
- [x] Accordian widget for bibliographic info
- [x] Set up subjects with BHL images & bibliographic data
- [x] Add a Groups page to select subjects by title (eg. Hardwicke's Science Gossip)
- [x] Cut Missouri Botanical Garden and Zooniverse text from the top
- [x] Add logos and project info to the about page
- [x] change 'Help catalogue scientific illustrations to 
- [x] add accordion style full page image so that even after you have cropped the image you can easily see the full page to extract data for the species etc as this info is not always in the image.
- [x] rearrange order of tasks to 1) box 2) id. species, inscription, contributors; 3) Illustration type 4) talk/ keywords
- [x] update title and project prose after 9 Feb once new name and text is confirmed.
- [x] Change 'painter' to 'artist'
- [x] link new blog: 'science gossip' 
- [x] merge 'team' and 'about' pages and add info for each person and team
- [x] update 'About text' from drive. Minor changes made at 11.53am on 16 Feb
- [x] change 'click finished' to 'click finish' 
- [x] Sometimes I can't add species or other tag information because the bottom part of the image gets cut off after things zoom in. Maybe we need to go one box at a time. 
- [x] Change 'Species' to 'Species/Subject'
- [x] update tutorial text
